# Generated by Django 2.2 on 2021-05-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_dragon_my_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='riders_that_like_me',
            field=models.ManyToManyField(related_name='dragons_liked', to='first_app.Rider'),
        ),
    ]
